fix: bluetooth save state
pop-os/default-settings pull request #145
Opened 2022-06-30 06:25 UTC by pbui

This is a follow up to #144 that handles the situation where there are
multiple bluetooth entries in /var/lib/systemd/rfkill.  The current
version would lead to a shell error and would not save the state
properly.  This new version sorts the output of the bluetooth entries
and picks the highest one.

Moreover, storing a system-level runtime file in /home/$USER seems
inappropriate.  This new version stores the bluetooth state file in
/run, which is where such things normally are stored.

I've also introduced a few variables to make the code a bit cleaner.

2022-06-30 06:28 UTC, pbui commented
As noted in https://github.com/pop-os/default-settings/pull/144, the current version of the script does not work if there are multiple bluetooth entries:

```
$ ls  /var/lib/systemd/rfkill/*bluetooth
/var/lib/systemd/rfkill/pci-0000:00:14.0-usb-0:7:1.0:bluetooth
/var/lib/systemd/rfkill/pci-0000:00:14.0-usb-0:7:bluetooth
/var/lib/systemd/rfkill/platform-dell-laptop:bluetooth
```

On such system, the original `if` condition fails:

```
$ [ $(cat /var/lib/systemd/rfkill/*bluetooth) -eq 0 ]
-bash: [: too many arguments
```

This new version resolves this by sorting the bluetooth entries and picking the one with the higest value.

Moreover, storing a system-level runtime file in `/home/$USER` seems inappropriate.  Likewise it is not clear that `$USER` is defined within the context of the systemd sleep hook.  So instead, I've updated the script to store the state file in `/run` where these things typically go.

2022-06-30 13:23 UTC, n3m0-22 requested changes
This is working well under most conditions, but there is a case where it will fail.

Steps to reproduce:

  1.  turn on built in bluetooth
  2. add a usb bluetooth adapter
  3. turn off bluetooth ( this will turn off both the usb and internal bluetooth )
  4. unplug usb bluetooth adapter
  5. turn on built in bluetooth

This creates a condition where `cat /var/lib/systemd/rfkill/*bluetooth` will return:
```
1
0
```

In this situation the internal bluetooth is on, but the script will still pick the highest value. In this case the highest value 1 is the now unplugged usb bluetooth adapter. This will cause the script to not run `rfkill block bluetooth` and prevent suspend since the internal bluetooth is on. 

Maybe this can be accounted for by adding a variable like the following.

`BT_DEVICE_COUNT=$(bluetoothctl list | wc -l)`

The output of this could be used to check if there is more than one bluetooth adapter in use.

2022-06-30 14:38 UTC, jackpot51 commented
Please quote all shell variables

2022-06-30 17:24 UTC, pbui commented
I have updated the PR to quote all shell variables.

@n3m0-22 Would it make sense to sort the bluetooth states and select the lowest value?  That way if you have `1 0`, you would select `0` and then call `rfkill block`.  Basically if any bluetooth device is in the `0` state, then we need to block it before suspend.

Otherwise, I'm not sure how to use the `BT_DEVICE_COUNT` variable you are suggesting.

2022-06-30 17:41 UTC, pbui commented
Nevermind about selecting the lowest value... that doesn't work.

2022-06-30 17:59 UTC, n3m0-22 commented
I was thinking about something like this. It could probably be done in a better way, but so far it's working for me. Of course this will only work with up to two bluetooth devices.
```
#!/bin/sh

set -e

BT_BLOCK_PATH=/run/bluetooth.blocked
BT_DEVICE_COUNT=$(bluetoothctl list | wc -l)

case "$2" in
    suspend | hybrid-sleep)
        case "$1" in
            pre)
                case "$BT_DEVICE_COUNT" in
                2)
                    BT_BLOCK_VALUE=$(cat /var/lib/systemd/rfkill/*bluetooth | sort -r | head -n 1)
                    case "$BT_BLOCK_VALUE" in
                    0)
                        rfkill block bluetooth
                        ;;
                    1)
                        > "$BT_BLOCK_PATH"
                        ;;
                    esac
                    ;;
                1)
                    BT_BLOCK_VALUE=$(cat /var/lib/systemd/rfkill/*bluetooth | sort | head -n 1)
                    case "$BT_BLOCK_VALUE" in
                    0)
                        rfkill block bluetooth
                        ;;
                    1)
                        > "$BT_BLOCK_PATH"
                        ;;
                    esac                
                esac
                ;;
            post)
                [ ! -f "$BT_BLOCK_PATH" ] && rfkill unblock bluetooth
                rm "$BT_BLOCK_PATH" 2> /dev/null
                ;;
        esac
        ;;
esac
```

2022-06-30 18:00 UTC, n3m0-22 commented
I see the new code you just pushed. It's definitely a simpler solution. I'll test it now.

2022-06-30 18:03 UTC, pbui commented
Rather than checking the entries in `/var/lib/systemd/rfkill/*bluetooth`, I have changed the code to parse the output of `rfkill`.  If any of the bluetooth devices listed are in the **unblocked** state, then the script will **block** all bluetooth devices before suspending.

This should work in the normal case and in the case @n3m0-22 mentions above.

The only problem with this is that if you have multiple devices in different states, then this will block all devices, and then unblock them if any one device is unblocked before suspend.  This is not a huge deal as most people do not have multiple bluetooth devices (and not in different states), but it is a possibility.

We could save and restore the state of each bluetooth device by parsing the output of `rfkill`, but before I attempt that, I'd like to know if that is something you'd want.

2022-06-30 18:21 UTC, n3m0-22 commented
I think using `rfkill -o ID,TYPE,SOFT | grep -q -E 'bluetooth\s+unblocked'` to obtain the device state is a better option since it will only show the attached devices eliminating the issue I listed above. I suppose it's possible someone could be using a bluetooth adapter to take the place of an older bluetooth device on their machine. It could cause an issue for them if they have the older bluetooth blocked and the newer running. In that case it would be good to save and restore or keep as is the state of each device.

2022-06-30 18:39 UTC, n3m0-22 commented
The current code is working well and solves the issues with multiple devices.

2022-06-30 19:43 UTC, n3m0-22 commented
I think it would be best to preserve the states of each device for restore on resume. We could use the json output of rfkill.

2022-06-30 20:38 UTC, n3m0-22 commented
This can be used to create a file with the ID and current state for each bluetooth device.
`rfkill -r -o ID,TYPE,SOFT | grep 'bluetooth' | awk '{print $1,$3}'`

2022-06-30 22:35 UTC, n3m0-22 commented
This still needs work, but I thought it would be good to share to move this along. It is mostly working, and keeps track of each bluetooth adapters state before suspend.

[pop-default-settings_bluetooth-suspend.txt](https://github.com/pop-os/default-settings/files/9023768/pop-default-settings_bluetooth-suspend.txt)

2022-07-01 07:01 UTC, n3m0-22 commented
The following is working for me. It saves and restores the states of all the bluetooth adapters.

```
#!/bin/sh

set -e

BT_BLOCK_PATH=/run/bluetooth.blocked
BT_STATES_PATH=/var/lib/systemd/rfkill/
BT_TMP_PATH=/tmp/

case "$2" in
    suspend | hybrid-sleep)
        case "$1" in
            pre)
                if rfkill -o ID,TYPE,SOFT | grep -q -E 'bluetooth\s+unblocked'; then
                    cp "$BT_STATES_PATH"*bluetooth "$BT_TMP_PATH"
                    rfkill block bluetooth
                else
                    > "$BT_BLOCK_PATH"
                fi
                ;;
            post)
                cp -f "$BT_TMP_PATH"*bluetooth "$BT_STATES_PATH"
                [ ! -f "$BT_BLOCK_PATH" ] && rfkill unblock bluetooth
                rm "$BT_BLOCK_PATH" 2> /dev/null
                rm "$BT_TMP_PATH"*bluetooth
                ;;
        esac
        ;;
esac

```

2022-07-01 09:02 UTC, pbui commented
> The following is working for me. It saves and restores the states of all the bluetooth adapters.
> 

I have updated the PR to use this version of the script (with minor changes to suppress error message for `cp` and `rm`).  This works for me, but I only have one bluetooth device on hand.

2022-07-01 15:51 UTC, n3m0-22 approved these changes
This is now working.

2022-07-01 16:40 UTC, crawfxrd approved these changes

2022-07-01 17:34 UTC, ids1024 approved these changes
I was going to question if the `rfkill` output might change by system locale, but it seems like it doesn't, and is designed to be parsable when used with `--output`.

And yeah, using `/home/$USER/blocked.bt` here doesn't seem right.

This looks good assuming it works as expected.

2022-07-05 14:59 UTC, merged