fix: Opt out of phased updates
pop-os/default-settings pull request #167
Opened 2023-03-06 23:49 UTC by n3m0-22

Phased updates messages have started showing up in Focal.

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
#
# "Phased updates" allow careful rollout of deb package changes at scale.
# You may see these as packages that have been "kept back". Learn more at
# https://ubuntu.com/server/docs/about-apt-upgrade-and-phased-updates
#
The following packages have been kept back:
  fwupd-signed
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

This is an addition of the original fix for Jammy. https://github.com/pop-os/default-settings/pull/153

2023-03-07 00:24 UTC, leviport commented
I don't think it worked: 
![2023-03-06_17-23-44](https://user-images.githubusercontent.com/13512097/223286829-6d1f8da0-de4b-4171-9f0d-86e2a8f4a0a8.png)

2023-03-07 16:32 UTC, ahoneybun commented
Wouldn't it be like this?:

APT::Get::Always-Include-Phased-Updates "false";

2023-03-07 16:35 UTC, leviport commented
@ahoneybun did you see https://github.com/pop-os/default-settings/pull/153 ?

2023-03-07 19:35 UTC, jackpot51 submitted a review, later dismissed

2023-03-08 00:25 UTC, leviport commented
I might need to wait a bit longer for the cron job to run, but I still got the phased updates message after installing this update and rebooting:
![2023-03-07_17-24-03](https://user-images.githubusercontent.com/13512097/223587005-523dbea5-7774-4e1d-9bc4-8a064f313fdd.png)

I'd also like an engineering opinion on whether this is the kind of fix we'd be happy with.

2023-03-08 02:18 UTC, jackpot51 commented
I expected this to work because it matches the jammy change. I would want the same thing on focal, once it works.

2023-03-08 15:25 UTC, n3m0-22 commented
My reasoning for going beyond what was done for Jammy is that in Focal while `APT::Get::Always-Include-Phased-Updates "true";` does seem to opt out of phased updates it does not suppress the message from Ubuntu when running `apt upgrade`.

My concern with this is that users will still be seeing a message about phased updates with a link to Ubuntu server docs https://ubuntu.com/server/docs/about-apt-upgrade-and-phased-updates.

I do see a difference in the version of `apt` that may be part of the problem (i.e., Jammy `apt` is `2.4.8`, Focal `apt` is `2.0.6`).

I also noticed that in `/etc/apt/apt.conf.d` on Jammy there is no file `20apt-esm-hook.conf`, but there is on Focal. If this file is deleted or it's contents commented out on Focal the message does go away. Maybe removing this file on Focal is a more acceptable solution.  

If this message showing is not of concern I can remove the second commit, and it should still opt out the user.

2023-03-08 15:34 UTC, 13r0ck commented
> but ubuntu-advantage-tools is now providing

Man we really need to improve our metapackaing to remove that package

2023-03-08 15:37 UTC, n3m0-22 commented
> > but `ubuntu-advantage-tools` is now providing
> 
> Man we really need to improve our metapackaing to remove that package

If removing the package completely is ok I can confirm from my testing that solves the issue as well.

2023-03-08 20:40 UTC, 13r0ck requested changes
Rather than running everytime the system boots, this should just be in https://github.com/pop-os/default-settings/blob/master_jammy/usr/bin/pop-app-folders

And run `pro config unset apt_news` once

2023-03-08 22:26 UTC, n3m0-22 commented
> Rather than running everytime the system boots, this should just be in https://github.com/pop-os/default-settings/blob/master_jammy/usr/bin/pop-app-folders
> 
> And run `pro config unset apt_news` once

I had thought about doing that, but I was worried an update to `ubuntu-advantage-tools` might reset the change. Although I suppose an update could also make this fix invalid anyway.

2023-03-13 23:17 UTC, n3m0-22 commented
On a fresh install of Pop 20.04, with or without the changes in this PR, I'm no longer seeing any messages about phased updates. Checking `pro config show` I'm seeing `apt_news` set to `true`. This PR may no longer be necessary, but that will need to be double checked.

2023-03-14 00:08 UTC, 13r0ck requested changes
Sorry for the delay. This should be wrapped in the check for cache version, i.e.:
```bash
if [ "${CACHE_VERSION}" -lt "1" ]
```
So it only runs once. I know you said that you arn't seeing the issue anymore, but it won't hurt to add this encase it comes back. After this change we should merge this.

2023-03-14 15:04 UTC, 13r0ck requested changes

2023-03-14 15:04 UTC, 13r0ck commented on usr/bin/pop-app-folders
> +if [ "${CACHE_VERSION}" -lt "1" ]
Still not quite there. Look at the app-folders file on jammy. The cache version needs to be iterated after each check, and the if statement needs to increase by each time as well

2023-03-14 15:21 UTC, 13r0ck approved these changes, later dismissed
Looks good!

2023-03-14 20:59 UTC, n3m0-22 commented
I'm closing this for now as it is not working. I will reopen if the issues presents itself again.

2023-03-23 20:01 UTC, jacobgkau approved these changes
Before installing:
![Screenshot from 2023-03-23 13-58-42](https://user-images.githubusercontent.com/7199422/227337396-c1d9fb4d-2d4b-4a45-a64a-77e5706d044b.png)
After installing:
![Screenshot from 2023-03-23 13-59-26](https://user-images.githubusercontent.com/7199422/227337411-e5b3cd3d-cd78-48b9-941c-adc1f6617a53.png)
Regarding https://github.com/pop-os/default-settings/pull/166#issuecomment-1478390144, in my Focal test environment, I did see the `leaving diversion of ...` messages when doing `apt upgrade` that would indicate the configure script ran.

2023-03-31 14:37 UTC, jackpot51 approved these changes

2023-03-31 14:37 UTC, merged